# Generated by Django 4.2 on 2025-05-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
