# Generated by Django 4.2 on 2025-07-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
