# Generated by Django 4.2 on 2025-05-04 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0002_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hired', models.DateField()),
                ('position', models.CharField(max_length=100)),
                ('educational_attainment', models.CharField(choices=[('High School', 'High School'), ('College', 'College'), ('Postgraduate', 'Postgraduate'), ('Others', 'Others')], max_length=50)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('fund_source', models.CharField(max_length=100)),
                ('tax_declaration', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eligibility', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='employee_attachments/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='payslip_generation_system.employee')),
            ],
        ),
    ]
