# Generated by Django 4.2 on 2025-05-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0003_employee_employeeattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fullname',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
