# Generated by Django 4.2 on 2025-05-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0004_employee_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='educational_attainment',
            field=models.CharField(blank=True, choices=[('High School', 'High School'), ('College', 'College'), ('Postgraduate', 'Postgraduate'), ('Others', 'Others')], max_length=50, null=True),
        ),
    ]
