# Generated by Django 4.2 on 2025-05-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0005_alter_employee_educational_attainment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tax_declaration',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
    ]
