# Generated by Django 4.2 on 2025-05-04 09:43

from django.db import migrations, models
import payslip_generation_system.models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0006_alter_employee_tax_declaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattachment',
            name='file',
            field=models.FileField(upload_to=payslip_generation_system.models.generate_random_filename),
        ),
    ]
