# Generated by Django 4.2 on 2025-05-05 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0008_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payslip_generation_system.employee'),
        ),
    ]
