# Generated by Django 4.2 on 2025-05-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0009_adjustment_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='cutoff',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], max_length=10),
        ),
    ]
