# Generated by Django 4.2 on 2025-05-05 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0010_adjustment_month_alter_adjustment_cutoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payslip_generation_system.employee'),
        ),
    ]
